( wdt )

[ifdef] wdp3   s" wdp3"   link, wdp3   const, [then]
[ifdef] wdce   s" wdce"   link, wdce   const, [then]
[ifdef] wde    s" wde"    link, wde    const, [then]
[ifdef] wdp2   s" wdp2"   link, wdp2   const, [then]
[ifdef] wdp1   s" wdp1"   link, wdp1   const, [then]
[ifdef] wdtcsr s" wdtcsr" link, wdtcsr const, [then]
[ifdef] wdif   s" wdif"   link, wdif   const, [then]
[ifdef] wdie   s" wdie"   link, wdie   const, [then]
[ifdef] wdp3   s" wdp3"   link, wdp3   const, [then]
[ifdef] wdce   s" wdce"   link, wdce   const, [then]
[ifdef] wde    s" wde"    link, wde    const, [then]
[ifdef] wdp2   s" wdp2"   link, wdp2   const, [then]
[ifdef] wdp1   s" wdp1"   link, wdp1   const, [then]
[ifdef] wdp0   s" wdp0"   link, wdp0   const, [then]

[ifdef] wdrf   s" wdrf"   link, wdrf   const, [then]
[ifdef] borf   s" borf"   link, borf   const, [then]
[ifdef] extrf  s" extrf"  link, extrf  const, [then]
[ifdef] porf   s" porf"   link, porf   const, [then]
[ifdef] mcusr  s" mcusr"  link, mcusr  const, [then]
